### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ArmA-UI-Editor#33]
If there would be an option for text-alignemnt that would be amazing!
(See [here](http://killzonekid.com/arma-scripting-tutorials-gui-part-4/) for how it works in ArmA)

**Comment by X39** [comment]
requires improvements in AddIns
currently not implemented due to too many different styles to maintain and check

feel free to create a PR
https://github.com/X39/ArmA-UI-Editor/tree/master/ArmA%20UI%20Editor/AddIns/Base/Properties
https://github.com/X39/ArmA-UI-Editor/blob/master/ArmA%20UI%20Editor/AddIns/Base/info.xml

https://github.com/X39/ArmA-UI-Editor/wiki/AddIn_Documentation
